package store

import(
 "context"
 "time"
 "github.com/google/uuid"
)
type MetricSample struct{Created time.Time;Status string;Input,Output,Reasoning,TTFT,Duration,Generation *int64}
func(s *Store)MetricSamples(ctx context.Context,from,to time.Time)([]MetricSample,error){rows,e:=s.pool.Query(ctx,"select created_at,status,input_tokens,output_tokens,reasoning_tokens,ttft_ms,duration_ms,generation_ms from api_request_history where created_at >= $1 and created_at < $2 order by created_at",from,to);if e!=nil{return nil,e};defer rows.Close();var out []MetricSample;for rows.Next(){var x MetricSample;if e=rows.Scan(&x.Created,&x.Status,&x.Input,&x.Output,&x.Reasoning,&x.TTFT,&x.Duration,&x.Generation);e!=nil{return nil,e};out=append(out,x)};return out,rows.Err()}
type Alert struct{ID uuid.UUID `json:"id"`;Severity string `json:"severity"`;Code string `json:"code"`;Message string `json:"message"`;State string `json:"state"`;Occurrences int64 `json:"occurrences"`;FirstSeen time.Time `json:"first_seen_at"`;LastSeen time.Time `json:"last_seen_at"`}
func(s *Store)Alerts(ctx context.Context,c *Cursor,limit int)([]Alert,*Cursor,error){q:="select id,severity,code,message,state,occurrences,first_seen_at,last_seen_at from api_alerts";args:=[]any{};if c!=nil{q+=" where (last_seen_at,id)<($1,$2)";args=append(args,c.At,c.ID)};q+=" order by last_seen_at desc,id desc limit $"+string(rune('1'+len(args)));args=append(args,limit+1);rows,e:=s.pool.Query(ctx,q,args...);if e!=nil{return nil,nil,e};defer rows.Close();var out []Alert;for rows.Next(){var x Alert;if e=rows.Scan(&x.ID,&x.Severity,&x.Code,&x.Message,&x.State,&x.Occurrences,&x.FirstSeen,&x.LastSeen);e!=nil{return nil,nil,e};out=append(out,x)};var next *Cursor;if len(out)>limit{x:=out[limit-1];out=out[:limit];next=&Cursor{x.LastSeen,x.ID}};return out,next,rows.Err()}
type Log struct{ID int64 `json:"id"`;At time.Time `json:"occurred_at"`;Level string `json:"level"`;Code string `json:"event_code"`;Message string `json:"message"`;RequestID *uuid.UUID `json:"request_id"`;OperationID *uuid.UUID `json:"operation_id"`}
func(s *Store)Logs(ctx context.Context,lastID *int64,limit int,level string)([]Log,*int64,error){q:="select id,occurred_at,level,event_code,request_id,operation_id,message from api_safe_logs where ($1::bigint is null or id<$1) and ($2='' or level=$2) order by occurred_at desc,id desc limit $3";rows,e:=s.pool.Query(ctx,q,lastID,level,limit+1);if e!=nil{return nil,nil,e};defer rows.Close();var out []Log;for rows.Next(){var x Log;if e=rows.Scan(&x.ID,&x.At,&x.Level,&x.Code,&x.RequestID,&x.OperationID,&x.Message);e!=nil{return nil,nil,e};out=append(out,x)};var next *int64;if len(out)>limit{v:=out[limit-1].ID;out=out[:limit];next=&v};return out,next,rows.Err()}
type Run struct{Kind,Status string;Started time.Time;Completed,Cutoff *time.Time;Affected,RequestCount,Input,Output,Reasoning *int64;Artifact,Error *string}
func(s *Store)LatestRuns(ctx context.Context)(map[string]Run,error){rows,e:=s.pool.Query(ctx,"select distinct on(kind) kind,status,started_at,completed_at,cutoff_at,affected_rows,request_count,input_tokens,output_tokens,reasoning_tokens,artifact_name,error_code from api_operational_runs order by kind,started_at desc");if e!=nil{return nil,e};defer rows.Close();out:=map[string]Run{};for rows.Next(){var x Run;if e=rows.Scan(&x.Kind,&x.Status,&x.Started,&x.Completed,&x.Cutoff,&x.Affected,&x.RequestCount,&x.Input,&x.Output,&x.Reasoning,&x.Artifact,&x.Error);e!=nil{return nil,e};out[x.Kind]=x};return out,rows.Err()}
type ModelOperation struct{ID uuid.UUID `json:"id"`;Operation string `json:"operation"`;Status string `json:"status"`;Requested time.Time `json:"requested_at"`;Started time.Time `json:"started_at"`;Completed *time.Time `json:"completed_at"`;Result *string `json:"result_code"`;Observed *string `json:"observed_state"`}
func(s *Store)ModelOperations(ctx context.Context,limit int)([]ModelOperation,error){rows,e:=s.pool.Query(ctx,"select id,operation,status,requested_at,started_at,completed_at,result_code,observed_state from api_model_operations order by requested_at desc limit $1",limit);if e!=nil{return nil,e};defer rows.Close();out:=make([]ModelOperation,0);for rows.Next(){var x ModelOperation;if e=rows.Scan(&x.ID,&x.Operation,&x.Status,&x.Requested,&x.Started,&x.Completed,&x.Result,&x.Observed);e!=nil{return nil,e};out=append(out,x)};return out,rows.Err()}
func(s *Store)ActiveAlertCount(ctx context.Context)(int64,error){var n int64;e:=s.pool.QueryRow(ctx,"select count(*) from api_alerts where state='active'").Scan(&n);return n,e}
