package public
import("net/http/httptest";"strings";"testing")
func request(body string)*httptest.ResponseRecorder{return httptest.NewRecorder()}
func parse(t *testing.T,body string,chat bool)(Parsed,string){t.Helper();r:=httptest.NewRequest("POST","/v1/chat/completions",strings.NewReader(body));r.Header.Set("Content-Type","application/json");p,e:=parseRequest(r,chat,"openbmb/MiniCPM5-2B-Q4_K_M");if e!=nil{return p,e.Code};return p,""}
func TestConfiguredNameReplacesOriginal(t *testing.T){for _,tc:=range []struct{model,code string}{{"team/model-v2",""},{"openbmb/MiniCPM5-2B-Q4_K_M","unsupported_value"}}{r:=httptest.NewRequest("POST","/v1/chat/completions",strings.NewReader(`{"model":"`+tc.model+`","messages":[{"role":"user","content":"x"}]}`));r.Header.Set("Content-Type","application/json");_,e:=parseRequest(r,true,"team/model-v2");code:="";if e!=nil{code=e.Code};if code!=tc.code{t.Fatalf("model %q: got %q, want %q",tc.model,code,tc.code)}}}
func TestStrictRequestRejectsUnsupportedUnknownAndDuplicate(t *testing.T){cases:=[]struct{body,code string}{{`{"model":"openbmb/MiniCPM5-2B-Q4_K_M","messages":[{"role":"user","content":"x"}],"seed":1}`,"unsupported_parameter"},{`{"model":"openbmb/MiniCPM5-2B-Q4_K_M","messages":[{"role":"user","content":"x"}],"future":1}`,"unknown_parameter"},{`{"model":"openbmb/MiniCPM5-2B-Q4_K_M","messages":[{"role":"user","content":"x","content":"y"}]}`,"malformed_json"},{`{"model":"openbmb/MiniCPM5-2B-Q4_K_M","messages":[{"role":"user","content":"x","extra":true}]}`,"invalid_parameter"}};for _,tc:=range cases{_,code:=parse(t,tc.body,true);if code!=tc.code{t.Fatalf("%s: got %q want %q",tc.body,code,tc.code)}}}
func TestDefaultsAndReasoningIsolation(t *testing.T){p,code:=parse(t,`{"model":"openbmb/MiniCPM5-2B-Q4_K_M","messages":[{"role":"user","content":"x"}]}`,true);if code!=""||p.Chat.MaxTokens!=2048||p.Chat.Temperature!=.8||!p.Chat.Reasoning||p.Payload["reasoning_budget"]!=-1{t.Fatalf("bad defaults: %#v %s",p.Chat,code)};p,code=parse(t,`{"model":"openbmb/MiniCPM5-2B-Q4_K_M","messages":[{"role":"user","content":"x"}],"reasoning":false}`,true);if code!=""||p.Chat.Reasoning||p.Payload["reasoning_budget"]!=0{t.Fatalf("reasoning false not isolated")}}
func TestCompletionRejectsTools(t *testing.T){_,code:=parse(t,`{"model":"openbmb/MiniCPM5-2B-Q4_K_M","prompt":"x","tools":[]}`,false);if code!="unsupported_parameter"{t.Fatalf("got %s",code)}}
func TestChatRejectsUnrepresentableToolArguments(t *testing.T){_,code:=parse(t,`{"model":"openbmb/MiniCPM5-2B-Q4_K_M","messages":[{"role":"assistant","content":null,"tool_calls":[{"id":"call_1","type":"function","function":{"name":"weather","arguments":"not-json"}}]}]}`,true);if code!="invalid_parameter"{t.Fatalf("got %s",code)}}
func TestReasoningTranslatesToInternalTemplateKwargs(t *testing.T){for _,tc:=range []struct{value bool;budget int}{{true,-1},{false,0}}{body:=`{"model":"openbmb/MiniCPM5-2B-Q4_K_M","messages":[{"role":"user","content":"x"}],"reasoning":`+map[bool]string{true:"true",false:"false"}[tc.value]+`}`;p,code:=parse(t,body,true);if code!=""{t.Fatalf("reasoning=%v: %s",tc.value,code)};applyChatTemplateMode(&p);if p.Payload["reasoning_budget"]!=tc.budget{t.Fatalf("reasoning=%v budget=%v",tc.value,p.Payload["reasoning_budget"])};kwargs,ok:=p.Payload["chat_template_kwargs"].(map[string]any);if !ok||kwargs["enable_thinking"]!=tc.value{t.Fatalf("reasoning=%v kwargs=%#v",tc.value,p.Payload["chat_template_kwargs"])}}}
func TestPublicCannotSupplyChatTemplateKwargs(t *testing.T){_,code:=parse(t,`{"model":"openbmb/MiniCPM5-2B-Q4_K_M","messages":[{"role":"user","content":"x"}],"chat_template_kwargs":{"enable_thinking":false}}`,true);if code!="unknown_parameter"{t.Fatalf("got %s",code)}}
func TestEveryInferenceInjectsAuthoritativeStreamUsage(t *testing.T){cases:=[]struct{chat bool;body string;publicStream bool}{{true,`{"model":"openbmb/MiniCPM5-2B-Q4_K_M","messages":[{"role":"user","content":"x"}],"stream":true}`,true},{true,`{"model":"openbmb/MiniCPM5-2B-Q4_K_M","messages":[{"role":"user","content":"x"}]}`,false},{false,`{"model":"openbmb/MiniCPM5-2B-Q4_K_M","prompt":"x","stream":true}`,true},{false,`{"model":"openbmb/MiniCPM5-2B-Q4_K_M","prompt":"x"}`,false}};for _,tc:=range cases{p,code:=parse(t,tc.body,tc.chat);if code!=""{t.Fatalf("chat=%v: %s",tc.chat,code)};applyStreamUsage(&p);options,ok:=p.Payload["stream_options"].(map[string]any);if !ok||options["include_usage"]!=true||p.Payload["stream"]!=true{t.Fatalf("chat=%v payload=%#v",tc.chat,p.Payload)};if tc.chat&&p.Chat.Stream!=tc.publicStream||!tc.chat&&p.Completion.Stream!=tc.publicStream{t.Fatalf("public stream contract changed for %#v",tc)}}}
func TestPublicCannotSupplyStreamOptions(t *testing.T){_,code:=parse(t,`{"model":"openbmb/MiniCPM5-2B-Q4_K_M","messages":[{"role":"user","content":"x"}],"stream_options":{"include_usage":true}}`,true);if code!="unsupported_parameter"{t.Fatalf("got %s",code)}}
