package retention
import("context";"time";"github.com/google/uuid";"github.com/jackc/pgx/v5/pgxpool")
type Scheduler struct{pool *pgxpool.Pool}
func Open(ctx context.Context,dsn string)(*Scheduler,error){p,e:=pgxpool.New(ctx,dsn);if e!=nil{return nil,e};if e=p.Ping(ctx);e!=nil{p.Close();return nil,e};s:=&Scheduler{p};if e=s.CatchUp(ctx);e!=nil{p.Close();return nil,e};return s,nil}
func(s *Scheduler)Close(){s.pool.Close()}
func(s *Scheduler)CatchUp(ctx context.Context)error{for range 24{var bucket *time.Time;if e:=s.pool.QueryRow(ctx,"select next_closed_aggregation_bucket()").Scan(&bucket);e!=nil{return e};if bucket==nil||!bucket.Before(time.Now().UTC().Truncate(time.Hour)){break};id,_:=uuid.NewV7();if _,e:=s.pool.Exec(ctx,"select aggregate_closed_hour($1,$2)",*bucket,id);e!=nil{return e}};var last *time.Time;if e:=s.pool.QueryRow(ctx,"select max(completed_at) from api_operational_runs where kind='retention' and status='succeeded'").Scan(&last);e!=nil{return e};now:=time.Now().UTC();if last==nil||last.UTC().Format("20060102")!=now.Format("20060102"){id,_:=uuid.NewV7();if _,e:=s.pool.Exec(ctx,"select * from purge_expired_metadata($1)",id);e!=nil{return e}};return nil}
func(s *Scheduler)Run(ctx context.Context){s.catchup(ctx);t:=time.NewTicker(time.Minute);defer t.Stop();lastHour:="";lastDay:="";for{select{case<-ctx.Done():return;case now:=<-t.C:u:=now.UTC();if u.Minute()>=5{key:=u.Format("2006010215");if key!=lastHour{s.catchup(ctx);lastHour=key}};if u.Hour()>2||(u.Hour()==2&&u.Minute()>=15){key:=u.Format("20060102");if key!=lastDay{s.retention(ctx);lastDay=key}}}}}
func(s *Scheduler)catchup(ctx context.Context){for range 24{var bucket *time.Time;if e:=s.pool.QueryRow(ctx,"select next_closed_aggregation_bucket()").Scan(&bucket);e!=nil||bucket==nil||!bucket.Before(time.Now().UTC().Truncate(time.Hour)){return};id,_:=uuid.NewV7();if _,e:=s.pool.Exec(ctx,"select aggregate_closed_hour($1,$2)",*bucket,id);e!=nil{return}}}
func(s *Scheduler)retention(ctx context.Context){var last *time.Time;_ = s.pool.QueryRow(ctx,"select max(completed_at) from api_operational_runs where kind='retention' and status='succeeded'").Scan(&last);now:=time.Now().UTC();if last!=nil&&last.UTC().Format("20060102")==now.Format("20060102"){return};id,_:=uuid.NewV7();_,_=s.pool.Exec(ctx,"select * from purge_expired_metadata($1)",id)}
